### ISSUE TITLE
Considering using swordjs

### ISSUE THREAD

**Issue by SimonBiggs** [zefanja/swordjs#12]
Hi,

I'm considering building a static bible study web app based on Angular 2 that uses swordjs. It would be heavily inspired by http://biblewebapp.com/study/ except it would be designed to be offline first.

Do you think I should go with swordjs? Or would you recommend another tool? I saw that you didn't have much luck with emscripten. Do you know if it might be worth my while trying that again? Or would it be better to use this tool here?

Thank you,
Simon

**Comment by zefanja** [comment]
AFAIK there is no other JavaScript library to access the sword modules, so there are not to much options... Sadly I do not have much free time to maintain this library - at least currently. 

Accessing modules (bibles and commentaries) should work and also basic rendering. But main features are still missing like a search function. The OSIS filter needs to be improved, too. 

So if you don't fear to put some effort in swordjs itself - feel free to use it :) 

I've tried emscripten several times, but couldn't get it working (actually I was, but not in a usable way). That's why I've started swordjs.

**Comment by SimonBiggs** [comment]
My other thought was to simply download all Bibles that have distribution
licenses compatible with GPL, then make use of the mod2imp script to read
the files locally. Then see if I can turn the imp files to json and simply
rehost them on Github.

Does that seem like a more plausible solution to the problem?

I miss out on a lot of the Bibles, but at least I then provide them in a
format that is easy to use and flexible.

**Comment by zefanja** [comment]
You can do this - but as you said - you will miss a lot of them. But you can ask the people behind the [STEP-Bible](https://www.stepbible.org/) project, I guess they have something similar.

**Comment by SimonBiggs** [comment]
It looks like they are pulling the Bibles server side with jsword. This
confuses me though as doesn't that then count as a redistribution? That
would once again cut out a lot of the bibles available for use.

**Comment by SimonBiggs** [comment]
I think I'll take swordjs for a spin, I really only want the module pulling
and parsing.

For my IndexedDB wrapper I would prefer to use Dexiejs. I'll see if I can
pull out the pertinent bits and get it to work.

Thank you. I'll let you know how I go.

By the way, do you know if the sword project has produced a JSON API? If
they have that really would be the perfect solution to all this...

On Mon, 28 Nov 2016, 12:32 AM Simon Biggs <mail@simonbiggs.net> wrote:

It looks like they are pulling the Bibles server side with jsword. This
confuses me though as doesn't that then count as a redistribution? That
would once again cut out a lot of the bibles available for use.

On Mon, 28 Nov 2016, 12:27 AM zefanja <notifications@github.com> wrote:

You can do this - but as you said - you will miss a lot of them. But you
can ask the people behind the STEP-Bible <https://www.stepbible.org/>
project, I guess they have something similar.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zefanja/swordjs/issues/12#issuecomment-263122121>, or mute
the thread

**Comment by zefanja** [comment]
> By the way, do you know if the sword project has produced a JSON API? If they have that really would be the perfect solution to all this...

No, the libsword (C++/Java) library is the only supported way to access the modules.

**Comment by SimonBiggs** [comment]
Thanks for your help
